### ISSUE TITLE
Makefile (static)

### ISSUE THREAD

**Issue by mhvduque** [mhvduque/pipex#4]

**Comment by fpedrazav02** [comment]
Por hacer

- Meter los .C en src de cada proyecto 
- Meter los .H en inc

Una vez las carpetas estén hechas hacer un Makefile que sea capaz de compilar los paquetes le vayamos incluyendo. 
- Generar una variable por cada src... y luego hacer un append de todas o compile por separado

**Comment by fpedrazav02** [comment]
@mhvduque El objetivo es tener un Makefile en la folder src del pipex que llame a compilar a la librería static como; 

- static.a y compile pipex.c para generar el bin --> pipex
- -> Para ello hace falta primero hacer el Makefile Static y luego el Makefile del proyecto
